### PR TITLE
DRUP-761 Move API product access tab

### PR DESCRIPTION
**Pull request by cnovak**
#189 Move API Product access tab from developer settings to API product settings

### CODE REVIEW

**Comment by mxr576** [comment]
@cnovak API product access tab moved from Products to Developers to avoid confusion and ensure consistency when Team API product had been introduced. #121 
I think if it would be displayed under "API products" and Team module is enabled, end-users may think that the configuration they provide on this UI also controls the API product access on the team level, but it does not. We could figure out a better way to display developer- and team API product access settings on the admin UI, but I do not think that moving _only_ the developer API product access under API products would be better than the current solution.

Also, the change you made probably require some adjustments in tests as well because changing routes should not be this easy. (This is what Travis CI build links could confirm.)

**Review by mxr576 — DISMISSED** [review]
See my comment above.

**Comment by mxr576** [comment]
(Missing JIRA issue number reference)

**Comment by cnovak** [comment]
I will have to validate tests, will add that.  I referenced the GitHub bug number in this PR instead of JIRA.

**Comment by mxr576** [comment]
> I referenced the GitHub bug number in this PR instead of JIRA.
But aren't all GH issues/PRs should be a reference in JIRA? So they could be scheduled for a sprint.

**Review by Jaesin — APPROVED** [review]
LGTM:

image

**Pull request merged**
