### PR TITLE
Make sure that cron runner starts executing the job

### PR DESCRIPTION
**Pull request by mxr576**
This is a follow up on #808 and #802.

@ycecube was right in 802, 808 is not enough. By examining the call stack difference between `drush queue:run apigee_edge_job` and `drush cron` after Background sync is initiated, I believe there is a typo on the `hook_cron()` implementation that prevents the execution of those queue items that are created by a job.

### CODE REVIEW

**Comment by mxr576** [comment]
@giteshk @phdhiren  This should have been landed in https://www.drupal.org/project/apigee_edge/releases/2.0.10 because without that [808](https://github.com/apigee/apigee-edge-drupal/pull/808) was not enough... :(

**Comment by giteshk** [comment]
@mxr576 we will test PR and merge it in the next release.

**Comment by mxr576** [comment]
Thank you!

**Review by shishir-intelli — APPROVED** [review]
LGTM

**Pull request merged**
