### PR TITLE
Aggregate cacheability information from access results

### LINKED ISSUE #1062: Cacheability information is lost when team based API product access is calculated
## Description

When `apigee_edge_teams_api_product_access()` calculated API product access based on whether a team (entity) has [operation] access to an API product it uses early return instead of returning the aggregated cacheability results from all evaluated access checks. (Which later may or may not be optimized by the caching system.)

## Apigee Info
N/A

## Steps to Reproduce
N/A

## Version Info
https://github.com/apigee/apigee-edge-drupal/commit/e22b578b1fa0387eb6a358fa5c572f0041fe1497

### PR DESCRIPTION
**Pull request by mxr576**
Ensure that cacheability information bubbles up from previously evaluated access results instead of just get lost.

Closes #1062.

### CODE REVIEW

**Comment by mxr576** [comment]
Just spotted this when I took a look at the source code.

Do we also need an issue for this?

**Comment by mxr576** [comment]
All failures look unrelated. 

```
 There were 4 errors:

1) Drupal\Tests\apigee_edge\Functional\DeveloperAppFieldTest::testFieldableDeveloperApp
Behat\Mink\Exception\ResponseTextException: The text "These settings apply to the GAS37JDF field everywhere it is used." was not found anywhere in the text of the current page.

/home/runner/work/apigee-edge-drupal/apigee-edge-drupal/drupal/vendor/behat/mink/src/WebAssert.php:9***7
/home/runner/work/apigee-edge-drupal/apigee-edge-drupal/drupal/vendor/behat/mink/src/WebAssert.php:293
/home/runner/work/apigee-edge-drupal/apigee-edge-drupal/drupal/core/modules/field_ui/tests/src/Traits/FieldUiTestTrait.php:85
/home/runner/work/apigee-edge-drupal/apigee-edge-drupal/drupal/modules/contrib/apigee_edge/tests/src/Functional/DeveloperAppFieldTest.php:263
/home/runner/work/apigee-edge-drupal/apigee-edge-drupal/drupal/modules/contrib/apigee_edge/tests/src/Functional/DeveloperAppFieldTest.php:121
/home/runner/work/apigee-edge-drupal/apigee-edge-drupal/drupal/vendor/phpunit/phpunit/src/Framework/TestResult.php:729

2) Drupal\Tests\apigee_edge\Functional\DeveloperSyncTest::testDeveloperSync
Behat\Mink\Exception\ElementNotFoundException: Form field with id|name|label|value "field_storage[subform][settings][allowed_values]" not found.

/home/runner/work/apigee-edge-drupal/apigee-edge-drupal/drupal/vendor/behat/mink/src/WebAssert.php:731
/home/runner/work/apigee-edge-drupal/apigee-edge-drupal/drupal/core/tests/Drupal/Tests/UiHelperTrait.php:85
/home/runner/work/apigee-edge-drupal/apigee-edge-drupal/drupal/core/modules/field_ui/tests/src/Traits/FieldUiTestTrait.php:1***5
/home/runner/work/apigee-edge-drupal/apigee-edge-drupal/drupal/modules/contrib/apigee_edge/tests/src/Functional/DeveloperSyncTest.php:382
/home/runner/work/apigee-edge-drupal/apigee-edge-drupal/drupal/modules/contrib/apigee_edge/tests/src/Functional/DeveloperSyncTest.php:147
/home/runner/work/apigee-edge-drupal/apigee-edge-drupal/drupal/vendor/phpunit/phpunit/src/Framework/TestResult.php:729

3) Drupal\Tests\apigee_edge\Functional\DeveloperSyncTest::testDeveloperAsync
Behat\Mink\Exception\ElementNotFoundException: Form field with id|name|label|value "field_storage[subform][settings][allowed_values]" not found.

/home/runner/work/apigee-edge-drupal/apigee-edge-drupal/drupal/vendor/behat/mink/src/WebAssert.php:731
/home/runner/work/apigee-edge-drupal/apigee-edge-drupal/drupal/core/tests/Drupal/Tests/UiHelperTrait.php:85
/home/runner/work/apigee-edge-drupal/apigee-edge-drupal/drupal/core/modules/field_ui/tests/src/Traits/FieldUiTestTrait.php:1***5
/home/runner/work/apigee-edge-drupal/apigee-edge-drupal/drupal/modules/contrib/apigee_edge/tests/src/Functional/DeveloperSyncTest.php:382
/home/runner/work/apigee-edge-drupal/apigee-edge-drupal/drupal/modules/contrib/apigee_edge/tests/src/Functional/DeveloperSyncTest.php:147
/home/runner/work/apigee-edge-drupal/apigee-edge-drupal/drupal/vendor/phpunit/phpunit/src/Framework/TestResult.php:729

4) Drupal\Tests\apigee_edge\Functional\DeveloperSyncTest::testCliDeveloperSync
Behat\Mink\Exception\ElementNotFoundException: Form field with id|name|label|value "field_storage[subform][settings][allowed_values]" not found.

/home/runner/work/apigee-edge-drupal/apigee-edge-drupal/drupal/vendor/behat/mink/src/WebAssert.php:731
/home/runner/work/apigee-edge-drupal/apigee-edge-drupal/drupal/core/tests/Drupal/Tests/UiHelperTrait.php:85
/home/runner/work/apigee-edge-drupal/apigee-edge-drupal/drupal/core/modules/field_ui/tests/src/Traits/FieldUiTestTrait.php:1***5
/home/runner/work/apigee-edge-drupal/apigee-edge-drupal/drupal/modules/contrib/apigee_edge/tests/src/Functional/DeveloperSyncTest.php:382
/home/runner/work/apigee-edge-drupal/apigee-edge-drupal/drupal/modules/contrib/apigee_edge/tests/src/Functional/DeveloperSyncTest.php:147
/home/runner/work/apigee-edge-drupal/apigee-edge-drupal/drupal/vendor/phpunit/phpunit/src/Framework/TestResult.php:729
```

**Comment by kedarkhaire** [comment]
> All failures look unrelated.
> 
> ```
>  There were 4 errors:
> 
> 1) Drupal\Tests\apigee_edge\Functional\DeveloperAppFieldTest::testFieldableDeveloperApp
> Behat\Mink\Exception\ResponseTextException: The text "These settings apply to the GAS37JDF field everywhere it is used." was not found anywhere in the text of the current page.
> 
> /home/runner/work/apigee-edge-drupal/apigee-edge-drupal/drupal/vendor/behat/mink/src/WebAssert.php:9***7
> /home/runner/work/apigee-edge-drupal/apigee-edge-drupal/drupal/vendor/behat/mink/src/WebAssert.php:293
> /home/runner/work/apigee-edge-drupal/apigee-edge-drupal/drupal/core/modules/field_ui/tests/src/Traits/FieldUiTestTrait.php:85
> /home/runner/work/apigee-edge-drupal/apigee-edge-drupal/drupal/modules/contrib/apigee_edge/tests/src/Functional/DeveloperAppFieldTest.php:263
> /home/runner/work/apigee-edge-drupal/apigee-edge-drupal/drupal/modules/contrib/apigee_edge/tests/src/Functional/DeveloperAppFieldTest.php:121
> /home/runner/work/apigee-edge-drupal/apigee-edge-drupal/drupal/vendor/phpunit/phpunit/src/Framework/TestResult.php:729
> 
> 2) Drupal\Tests\apigee_edge\Functional\DeveloperSyncTest::testDeveloperSync
> Behat\Mink\Exception\ElementNotFoundException: Form field with id|name|label|value "field_storage[subform][settings][allowed_values]" not found.
> 
> /home/runner/work/apigee-edge-drupal/apigee-edge-drupal/drupal/vendor/behat/mink/src/WebAssert.php:731
> /home/runner/work/apigee-edge-drupal/apigee-edge-drupal/drupal/core/tests/Drupal/Tests/UiHelperTrait.php:85
> /home/runner/work/apigee-edge-drupal/apigee-edge-drupal/drupal/core/modules/field_ui/tests/src/Traits/FieldUiTestTrait.php:1***5
> /home/runner/work/apigee-edge-drupal/apigee-edge-drupal/drupal/modules/contrib/apigee_edge/tests/src/Functional/DeveloperSyncTest.php:382
> /home/runner/work/apigee-edge-drupal/apigee-edge-drupal/drupal/modules/contrib/apigee_edge/tests/src/Functional/DeveloperSyncTest.php:147
> /home/runner/work/apigee-edge-drupal/apigee-edge-drupal/drupal/vendor/phpunit/phpunit/src/Framework/TestResult.php:729
> 
> 3) Drupal\Tests\apigee_edge\Functional\DeveloperSyncTest::testDeveloperAsync
> Behat\Mink\Exception\ElementNotFoundException: Form field with id|name|label|value "field_storage[subform][settings][allowed_values]" not found.
> 
> /home/runner/work/apigee-edge-drupal/apigee-edge-drupal/drupal/vendor/behat/mink/src/WebAssert.php:731
> /home/runner/work/apigee-edge-drupal/apigee-edge-drupal/drupal/core/tests/Drupal/Tests/UiHelperTrait.php:85
> /home/runner/work/apigee-edge-drupal/apigee-edge-drupal/drupal/core/modules/field_ui/tests/src/Traits/FieldUiTestTrait.php:1***5
> /home/runner/work/apigee-edge-drupal/apigee-edge-drupal/drupal/modules/contrib/apigee_edge/tests/src/Functional/DeveloperSyncTest.php:382
> /home/runner/work/apigee-edge-drupal/apigee-edge-drupal/drupal/modules/contrib/apigee_edge/tests/src/Functional/DeveloperSyncTest.php:147
> /home/runner/work/apigee-edge-drupal/apigee-edge-drupal/drupal/vendor/phpunit/phpunit/src/Framework/TestResult.php:729
> 
> 4) Drupal\Tests\apigee_edge\Functional\DeveloperSyncTest::testCliDeveloperSync
> Behat\Mink\Exception\ElementNotFoundException: Form field with id|name|label|value "field_storage[subform][settings][allowed_values]" not found.
> 
> /home/runner/work/apigee-edge-drupal/apigee-edge-drupal/drupal/vendor/behat/mink/src/WebAssert.php:731
> /home/runner/work/apigee-edge-drupal/apigee-edge-drupal/drupal/core/tests/Drupal/Tests/UiHelperTrait.php:85
> /home/runner/work/apigee-edge-drupal/apigee-edge-drupal/drupal/core/modules/field_ui/tests/src/Traits/FieldUiTestTrait.php:1***5
> /home/runner/work/apigee-edge-drupal/apigee-edge-drupal/drupal/modules/contrib/apigee_edge/tests/src/Functional/DeveloperSyncTest.php:382
> /home/runner/work/apigee-edge-drupal/apigee-edge-drupal/drupal/modules/contrib/apigee_edge/tests/src/Functional/DeveloperSyncTest.php:147
> /home/runner/work/apigee-edge-drupal/apigee-edge-drupal/drupal/vendor/phpunit/phpunit/src/Framework/TestResult.php:729
> ```

Hi @mxr576 
Those issue are due to the syntax update for select list options from Drupal 10.2.
We have worked on it in PR #1057 Once we merge that it will be fixed.

Thanks!

**Comment by kedarkhaire** [comment]
> Just spotted this when I took a look at the source code.
> 
> Do we also need an issue for this?

Hi @mxr576 
Yes it will better tif we have a ticket for this.
Thanks!

**Comment by mxr576** [comment]
Opened #1062.

**Review by kedarkhaire — APPROVED** [review]
LGTM

**Pull request merged**
