### PR TITLE
Adding http_client_proxy setting field

### PR DESCRIPTION
**Pull request by ngonendiaye**
image

### CODE REVIEW

**Comment by cnovak** [comment]
Thanks for the submission @ngonendiaye. Can you add more details on this feature request and what problem it is solving? It looks like this PR only has the UI, are you planning on adding the implementation also?

**Comment by ngonendiaye** [comment]
You're welcome. This feature request is for the UI only and allows easy configuration of the http_client_proxy variable for connections to Apigee edge.

**Comment by ngonendiaye** [comment]
@googlebot I signed it!

**Review by arlina-espinoza — APPROVED** [review]
Thanks @ngonendiaye , it looks like we already had all the code and were just missing exposing the field for configuration. I just fixed some codesniffer validations, and updated the proxy field message to make it clear that not everyone will need to set this field.

**Comment by cnovak** [comment]
@googlebot recheck CLA

**Comment by arlina-espinoza** [comment]
Closing in favor of #475 because it has the signed CLA.

**Pull request closed without merging**
