### PR TITLE
Fix config schema violation in apigee_edge_teams_update_8701()

### LINKED ISSUE #568: apigee_edge_teams_update_8701() conflicts with \Drupal\apigee_edge_teams\Form\TeamPermissionsForm::submitForm() via \Drupal\apigee_edge_teams\Entity\Storage\TeamRoleStorage::changePermissions()
## Description
As `apigee_edge_teams_update_8701()` calls `\Drupal\apigee_edge_teams\Entity\Storage\TeamRoleStorage::changePermissions()` differently than `\Drupal\apigee_edge_teams\Form\TeamPermissionsForm::submitForm()`.

Looks like `\Drupal\apigee_edge_teams\Entity\Storage\TeamRoleStorage::changePermissions()` is prepared for being called from `\Drupal\apigee_edge_teams\Form\TeamPermissionsForm::submitForm()` (the `array_filter()` call is there because of the unchecked checkboxes on the form).

The `apigee_edge_teams_update_8701()` tries to _add_ some more permissions to the already-existing ones a team role might have, but does it wrong: with a team role already having some permissions (that are coming in an array like `[0 => 'team_manage_members', 1 => 'team_app_delete', 2 => 'team_app_update']`), the new permissions it's gonna send to the storage will look something like `[0 => 'team_manage_members', 1 => 'team_app_delete', 2 => 'team_app_update', 'team_app_add_api_key' => 'team_app_add_api_key', 'team_app_edit_api_products' => 'team_app_edit_api_products', 'team_app_revoke_api_key' => 'team_app_revoke_api_key']`. Storage tries to use only the array _keys_ (since it's prepared for input coming from a form), so it's gonna try to save something like `['team_manage_members', 'team_app_delete', 'team_app_update', 1, 2, 'team_app_add_api_key', 'team_app_edit_api_products', 'team_app_revoke_api_key']`. This will cause a config schema violation, resulting in an error message.

## Steps to Reproduce
1. Install apigee_edge_teams.module as an old version that does not have this update hook yet.
2. Configure a team role to have at least one permission.
3. Update apigee_edge_teams.module to the latest version (that already has this update hook).
4. Run `drush updb`.

## Actual Behavior
An invalid config is stored, and with the config schema validator service enabled, an error message is also thrown:

```
>  [notice] Update started: apigee_edge_teams_update_8701
>  [error]  Schema errors for apigee_edge_teams.team_role.admin with the following errors: apigee_edge_teams.team_role.admin:permissions.3 variable type is integer but applied schema class is Drupal\Core\TypedData\Plugin\DataType\StringData, apigee_edge_teams.team_role.admin:permissions.4 variable type is integer but applied schema class is Drupal\Core\TypedData\Plugin\DataType\StringData 
>  [error]  Update failed: apigee_edge_teams_update_8701 
```

## Expected Behavior
The `apigee_edge_teams_update_8701()` grants the new permissions without violating config schema, therefore `drush updb` does not throw any error.

## Version Info
I was trying to update apigee_edge_teams.module from 1.13 to 1.21 (on Drupal core 8.9.13).

### PR DESCRIPTION
**Pull request by boobaa**
Closes #568

### CODE REVIEW

**Review by mxr576 — APPROVED** [review]

**Comment by raakesh-blokhra** [comment]
@boobaa I see some checks have not passed, can you please find out why it's failing.

**Comment by boobaa** [comment]
I'll need help with that, thanks.

**Comment by boobaa** [comment]
Those test failures are most likely false-positive ones, but definitely unrelated; can you please restart the build or run tests manually?

**Comment by phdhiren** [comment]
Let me check there

**Review by phdhiren — APPROVED** [review]
Thanks so much for the PR, we really appreciate you going out of your way to contribute to the issues. The changes look good. Please go ahead and 'Squash and merge' the code.

**Comment by boobaa** [comment]
Those test failures are false-positive ones and unrelated.

**Comment by phdhiren** [comment]
@boobaa,
I've rerun test cases and those have passed, you can go ahead and merge the code. Again thank you for the contribution.

**Review by mxr576 — APPROVED** [review]

**Comment by boobaa** [comment]
Looks like I don't have the rights to merge. Thank you for doing that.

**Pull request merged**
