### PR TITLE
Fix circleCI update_dependencies step

### LINKED ISSUE #436: Fix failing tests due to SQL error
## Description
We have tests failing because of `Drupal\Core\Database\DatabaseExceptionWrapper: SQLSTATE[HY000]: General error: 1 too many SQL variables`.

Seems to be related to https://github.com/apigee/apigee-edge-drupal/blob/8.x-1.x/tests/src/Functional/DeveloperAppUITestTrait.php#L342 which is loading all apps to find one.

## Steps to Reproduce
See circle ci logs.

## Notes
We should replace this by something like this:

```php
$storage->getQuery()
  ->condition('developerId', $developer->uuid())
  ->condition('name', $name)
  ->execute()
```

### PR DESCRIPTION
**Pull request by arlina-espinoza**
CircleCI workflows are failing in the update_dependencies step as seen in: https://app.circleci.com/pipelines/github/apigee/apigee-edge-drupal/128/workflows/ef21e046-108a-4822-8ce8-f6bf91b6e436/jobs/471

This PR should fix them.

### CODE REVIEW

**Comment by arlina-espinoza** [comment]
Should also fix #436 .

**Comment by shadcn** [comment]
> Should also fix #436 .

Still failing :(

**Review by minnur — COMMENTED** [review]
The tests are still failing for me

**Review by shadcn — APPROVED** [review]
LGTM 🚀

**Pull request merged**
