### PR TITLE
[#241] Handle exceptions for $entity->toUrl()

### LINKED ISSUE #241: Exception not handled for $entity->toUrl() in template_preprocess_apigee_entity
**Describe the bug**
In `template_preprocess_apigee_entity`, exceptions are not caught for `$entity->toUrl()`. This results in a fatal error if `toUrl()` fails.

**To Reproduce**
See https://github.com/apigee/apigee-m10n-drupal/issues/166

**Expected behavior**
Wrap into a try catch so that we do not see a fatal error.

### PR DESCRIPTION
**Pull request by shadcn**
Fixes #241

### CODE REVIEW

**Review by mxr576 — CHANGES_REQUESTED** [review]
Based on this explanation I think this PR should not be merged.

https://github.com/apigee/apigee-m10n-drupal/issues/166#issuecomment-512287020

**Comment by mxr576** [comment]
If you check usages of `toUrl()` in Drupal core you do not see that it would be try-catched either.

**Comment by mxr576** [comment]
@arshad @cnovak Can we close this PR as a proper fix for the real issue has been merged with https://github.com/apigee/apigee-m10n-drupal/pull/176?

**Comment by shadcn** [comment]
Sure

**Pull request closed without merging**
