### PR TITLE
Sync: prevent exception if username is too long

### PR DESCRIPTION
**Pull request by mxr576**
Developer sync does not handle properly if the username coming from Apigee Edge is longer than the default accepted length by Drupal (60 charachters as per [UserNameConstraintValidator](https://github.com/drupal/core/blob/8.8.x/modules/user/src/Plugin/Validation/Constraint/UserNameConstraintValidator.php#L56) and [UserInterface](https://github.com/drupal/core/blob/8.8.x/modules/user/src/UserInterface.php#L21)).

Before:
before

After:
after

### CODE REVIEW

**Comment by mxr576** [comment]
@arshad @arlina-espinoza @cnovak Hi, may I get a review on this?

**Comment by cnovak** [comment]
Reviewing it now, thanks for screenshots for clarification

**Review by cnovak — APPROVED** [review]
LGTM, confirmed exception in logs

**Comment by mxr576** [comment]
Thanks for the approval, I do not have permission to merge anymore, pls merge it.

**Comment by shadcn** [comment]
Merged. Thank you 👍

**Pull request merged**
