### PR TITLE
[#393] Drupal 9 deprecations fixes

### LINKED ISSUE #393: Drupal 9 readiness
Fix deprecation warnings for Drupal 9, and mark the module as compatible by adding `core_version_requirement: ^8 || ^9` to `apigee_edge.info.yml` and other module info files (https://www.drupal.org/node/3070687). 
The following report was generated using [mglaman/drupal-check](https://github.com/mglaman/drupal-check):

```
 ------ --------------------------------------------------------------------- 
  Line   apigee_edge.install                                                  
 ------ --------------------------------------------------------------------- 
  39     Call to deprecated function drupal_installation_attempted():         
         in drupal:8.8.0 and is removed from drupal:9.0.0.                    
         Use \Drupal\Core\Installer\InstallerKernel::installationAttempted()  
         instead.                                                             
 ------ --------------------------------------------------------------------- 

 ------ --------------------------------------------------------------------------------- 
  Line   apigee_edge.module                                                               
 ------ --------------------------------------------------------------------------------- 
  895    Call to deprecated method hashEquals() of class Drupal\Component\Utility\Crypt:  
         in drupal:8.8.0 and is removed from drupal:9.0.0.                                
         Use PHP's built-in hash_equals() function instead.                               
 ------ --------------------------------------------------------------------------------- 

 ------ ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
  Line   modules/apigee_edge_teams/src/Entity/Storage/TeamMemberRoleStorage.php                                                                                                                              
 ------ ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
  81     Parameter $entity_manager of method Drupal\apigee_edge_teams\Entity\Storage\TeamMemberRoleStorage::__construct() has typehint with deprecated interface Drupal\Core\Entity\EntityManagerInterface:  
         in drupal:8.0.0 and is removed from drupal:9.0.0.                                                                                                                                                   
 ------ ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 

 ------ ------------------------------------------------------------------------------------------------ 
  Line   modules/apigee_edge_teams/src/Form/AddTeamMembersForm.php                                       
 ------ ------------------------------------------------------------------------------------------------ 
  93     Call to deprecated method getLowercaseLabel() of class Drupal\Core\Entity\EntityTypeInterface:  
         in drupal:8.8.0 and is removed from drupal:9.0.0.                                               
         Instead, you should call getSingularLabel().                                                    
         See https://www.drupal.org/node/3075567                                                         
  120    Call to deprecated method getLowercaseLabel() of class Drupal\Core\Entity\EntityTypeInterface:  
         in drupal:8.8.0 and is removed from drupal:9.0.0.                                               
         Instead, you should call getSingularLabel().                                                    
         See https://www.drupal.org/node/3075567                                                         
  160    Call to deprecated method getLowercaseLabel() of class Drupal\Core\Entity\EntityTypeInterface:  
         in drupal:8.8.0 and is removed from drupal:9.0.0.                                               
         Instead, you should call getSingularLabel().                                                    
         See https://www.drupal.org/node/3075567                                                         
 ------ ------------------------------------------------------------------------------------------------ 

 ------ ------------------------------------------------------------------------------------------------ 
  Line   modules/apigee_edge_teams/src/Form/EditTeamMemberForm.php                                       
 ------ ------------------------------------------------------------------------------------------------ 
  85     Call to deprecated method getLowercaseLabel() of class Drupal\Core\Entity\EntityTypeInterface:  
         in drupal:8.8.0 and is removed from drupal:9.0.0.                                               
         Instead, you should call getSingularLabel().                                                    
         See https://www.drupal.org/node/3075567                                                         
 ------ ------------------------------------------------------------------------------------------------ 

 ------ ------------------------------------------------------------------------------------------------ 
  Line   modules/apigee_edge_teams/src/Form/RemoveTeamMemberForm.php                                     
 ------ ------------------------------------------------------------------------------------------------ 
  118    Call to deprecated method getLowercaseLabel() of class Drupal\Core\Entity\EntityTypeInterface:  
         in drupal:8.8.0 and is removed from drupal:9.0.0.                                               
         Instead, you should call getSingularLabel().                                                    
         See https://www.drupal.org/node/3075567                                                         
  137    Call to deprecated method getLowercaseLabel() of class Drupal\Core\Entity\EntityTypeInterface:  
         in drupal:8.8.0 and is removed from drupal:9.0.0.                                               
         Instead, you should call getSingularLabel().                                                    
         See https://www.drupal.org/node/3075567                                                         
  152    Call to deprecated method getLowercaseLabel() of class Drupal\Core\Entity\EntityTypeInterface:  
         in drupal:8.8.0 and is removed from drupal:9.0.0.                                               
         Instead, you should call getSingularLabel().                                                    
         See https://www.drupal.org/node/3075567                                                         
 ------ ------------------------------------------------------------------------------------------------ 

 ------ ------------------------------------------------------------------------------------------------ 
  Line   modules/apigee_edge_teams/src/Form/TeamRoleDeleteForm.php                                       
 ------ ------------------------------------------------------------------------------------------------ 
  45     Call to deprecated method getLowercaseLabel() of class Drupal\Core\Entity\EntityTypeInterface:  
         in drupal:8.8.0 and is removed from drupal:9.0.0.                                               
         Instead, you should call getSingularLabel().                                                    
         See https://www.drupal.org/node/3075567                                                         
 ------ ------------------------------------------------------------------------------------------------ 

 ------ ------------------------------------------------------------------------------------------------ 
  Line   modules/apigee_edge_teams/src/Form/TeamRoleForm.php                                             
 ------ ------------------------------------------------------------------------------------------------ 
  50     Call to deprecated method getLowercaseLabel() of class Drupal\Core\Entity\EntityTypeInterface:  
         in drupal:8.8.0 and is removed from drupal:9.0.0.                                               
         Instead, you should call getSingularLabel().                                                    
         See https://www.drupal.org/node/3075567                                                         
 ------ ------------------------------------------------------------------------------------------------ 

 ------ -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
  Line   modules/apigee_edge_teams/src/Plugin/EntityReferenceSelection/TeamMembersSelection.php                                                                                                                              
 ------ -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
  97     Parameter $entity_manager of method Drupal\apigee_edge_teams\Plugin\EntityReferenceSelection\TeamMembersSelection::__construct() has typehint with deprecated interface Drupal\Core\Entity\EntityManagerInterface:  
         in drupal:8.0.0 and is removed from drupal:9.0.0.                                                                                                                                                                   
 ------ -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 

 ------ ------------------------------------------------------------------------------------------------ 
  Line   modules/apigee_edge_teams/src/Plugin/Menu/AddAppForTeamLocalAction.php                          
 ------ ------------------------------------------------------------------------------------------------ 
  85     Call to deprecated method getLowercaseLabel() of class Drupal\Core\Entity\EntityTypeInterface:  
         in drupal:8.8.0 and is removed from drupal:9.0.0.                                               
         Instead, you should call getSingularLabel().                                                    
         See https://www.drupal.org/node/3075567                                                         
 ------ ------------------------------------------------------------------------------------------------ 

 ------ ------------------------------------------------------------------------------------------------ 
  Line   src/Entity/Form/AppCreateForm.php                                                               
 ------ ------------------------------------------------------------------------------------------------ 
  253    Call to deprecated method getLowercaseLabel() of class Drupal\Core\Entity\EntityTypeInterface:  
         in drupal:8.8.0 and is removed from drupal:9.0.0.                                               
         Instead, you should call getSingularLabel().                                                    
         See https://www.drupal.org/node/3075567                                                         
 ------ ------------------------------------------------------------------------------------------------ 

 ------ ------------------------------------------------------------------------------------------------ 
  Line   src/Entity/Form/AppForm.php                                                                     
 ------ ------------------------------------------------------------------------------------------------ 
  197    Call to deprecated method getLowercaseLabel() of class Drupal\Core\Entity\EntityTypeInterface:  
         in drupal:8.8.0 and is removed from drupal:9.0.0.                                               
         Instead, you should call getSingularLabel().                                                    
         See https://www.drupal.org/node/3075567                                                         
  198    Call to deprecated method getLowercaseLabel() of class Drupal\Core\Entity\EntityTypeInterface:  
         in drupal:8.8.0 and is removed from drupal:9.0.0.                                               
         Instead, you should call getSingularLabel().                                                    
         See https://www.drupal.org/node/3075567                                                         
 ------ ------------------------------------------------------------------------------------------------ 

 ------ ------------------------------------------------------------------------------------------------ 
  Line   src/Entity/Form/EdgeEntityDeleteForm.php                                                        
 ------ ------------------------------------------------------------------------------------------------ 
  119    Call to deprecated method getLowercaseLabel() of class Drupal\Core\Entity\EntityTypeInterface:  
         in drupal:8.8.0 and is removed from drupal:9.0.0.                                               
         Instead, you should call getSingularLabel().                                                    
         See https://www.drupal.org/node/3075567                                                         
  129    Call to deprecated method getLowercaseLabel() of class Drupal\Core\Entity\EntityTypeInterface:  
         in drupal:8.8.0 and is removed from drupal:9.0.0.                                               
         Instead, you should call getSingularLabel().                                                    
         See https://www.drupal.org/node/3075567                                                         
 ------ ------------------------------------------------------------------------------------------------ 

 ------ ------------------------------------------------------------------------------------------------ 
  Line   src/Entity/ListBuilder/AppListBuilder.php                                                       
 ------ ------------------------------------------------------------------------------------------------ 
  332    Call to deprecated method getLowercaseLabel() of class Drupal\Core\Entity\EntityTypeInterface:  
         in drupal:8.8.0 and is removed from drupal:9.0.0.                                               
         Instead, you should call getSingularLabel().                                                    
         See https://www.drupal.org/node/3075567                                                         
  346    Call to deprecated method getLowercaseLabel() of class Drupal\Core\Entity\EntityTypeInterface:  
         in drupal:8.8.0 and is removed from drupal:9.0.0.                                               
         Instead, you should call getSingularLabel().                                                    
         See https://www.drupal.org/node/3075567                                                         
  353    Call to deprecated method getLowercaseLabel() of class Drupal\Core\Entity\EntityTypeInterface:  
         in drupal:8.8.0 and is removed from drupal:9.0.0.                                               
         Instead, you should call getSingularLabel().                                                    
         See https://www.drupal.org/node/3075567                                                         
 ------ ------------------------------------------------------------------------------------------------ 

 ------ --------------------------------------------------------- 
  Line   src/Form/AppAnalyticsFormBase.php                        
 ------ --------------------------------------------------------- 
  200    Call to deprecated function drupal_get_user_timezone():  
         in drupal:8.8.0 and is removed from drupal:9.0.0. Use    
         date_default_timezone_get() instead.                     
  227    Call to deprecated function drupal_get_user_timezone():  
         in drupal:8.8.0 and is removed from drupal:9.0.0. Use    
         date_default_timezone_get() instead.                     
  229    Call to deprecated function drupal_get_user_timezone():  
         in drupal:8.8.0 and is removed from drupal:9.0.0. Use    
         date_default_timezone_get() instead.                     
  354    Call to deprecated function drupal_get_user_timezone():  
         in drupal:8.8.0 and is removed from drupal:9.0.0. Use    
         date_default_timezone_get() instead.                     
 ------ --------------------------------------------------------- 

 ------ ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
  Line   src/OauthTokenFileStorage.php                                                                                                                                                     
 ------ ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
  173    Call to deprecated constant FILE_EXISTS_REPLACE: Deprecated in drupal:8.7.0 and is removed from drupal:9.0.0. Use \Drupal\Core\File\FileSystemInterface::EXISTS_REPLACE.          
  173    Call to deprecated function file_unmanaged_save_data():                                                                                                                           
         in drupal:8.7.0 and is removed from drupal:9.0.0.                                                                                                                                 
         Use \Drupal\Core\File\FileSystemInterface::saveData().                                                                                                                            
  194    Call to deprecated constant FILE_CREATE_DIRECTORY: Deprecated in drupal:8.7.0 and is removed from drupal:9.0.0. Use \Drupal\Core\File\FileSystemInterface::CREATE_DIRECTORY.      
  194    Call to deprecated constant FILE_MODIFY_PERMISSIONS: Deprecated in drupal:8.7.0 and is removed from drupal:9.0.0. Use \Drupal\Core\File\FileSystemInterface::MODIFY_PERMISSIONS.  
  194    Call to deprecated function file_prepare_directory():                                                                                                                             
         in drupal:8.7.0 and is removed from drupal:9.0.0.                                                                                                                                 
         Use \Drupal\Core\File\FileSystemInterface::prepareDirectory().                                                                                                                    
  225    Call to deprecated function file_unmanaged_delete():                                                                                                                              
         in drupal:8.7.0 and is removed from drupal:9.0.0.                                                                                                                                 
         Use \Drupal\Core\File\FileSystemInterface::delete().                                                                                                                              
 ------ ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 

 ------ --------------------------------------------------------------------------------------- 
  Line   src/Plugin/Derivative/DynamicAddEntityLocalActions.php                                 
 ------ --------------------------------------------------------------------------------------- 
  102    Call to deprecated method getLowercaseLabel() of class Drupal\Core\Entity\EntityType:  
         in drupal:8.8.0 and is removed from drupal:9.0.0.                                      
         Instead, you should call getSingularLabel().                                           
         See https://www.drupal.org/node/3075567                                                
 ------ --------------------------------------------------------------------------------------- 

 ------ ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
  Line   src/Plugin/KeyProvider/PrivateFileKeyProvider.php                                                                                                                                 
 ------ ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
  137    Call to deprecated constant FILE_CREATE_DIRECTORY: Deprecated in drupal:8.7.0 and is removed from drupal:9.0.0. Use \Drupal\Core\File\FileSystemInterface::CREATE_DIRECTORY.      
  137    Call to deprecated constant FILE_MODIFY_PERMISSIONS: Deprecated in drupal:8.7.0 and is removed from drupal:9.0.0. Use \Drupal\Core\File\FileSystemInterface::MODIFY_PERMISSIONS.  
  137    Call to deprecated function file_prepare_directory():                                                                                                                             
         in drupal:8.7.0 and is removed from drupal:9.0.0.                                                                                                                                 
         Use \Drupal\Core\File\FileSystemInterface::prepareDirectory().                                                                                                                    
  140    Call to deprecated constant FILE_EXISTS_REPLACE: Deprecated in drupal:8.7.0 and is removed from drupal:9.0.0. Use \Drupal\Core\File\FileSystemInterface::EXISTS_REPLACE.          
  140    Call to deprecated function file_unmanaged_save_data():                                                                                                                           
         in drupal:8.7.0 and is removed from drupal:9.0.0.                                                                                                                                 
         Use \Drupal\Core\File\FileSystemInterface::saveData().                                                                                                                            
  148    Call to deprecated function file_unmanaged_delete():                                                                                                                              
         in drupal:8.7.0 and is removed from drupal:9.0.0.                                                                                                                                 
         Use \Drupal\Core\File\FileSystemInterface::delete().                                                                                                                              
 ------ ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 

 ------ ------------------------------------------------------------------------------------------------ 
  Line   src/Plugin/Menu/AddAppForDeveloperLocalAction.php                                               
 ------ ------------------------------------------------------------------------------------------------ 
  85     Call to deprecated method getLowercaseLabel() of class Drupal\Core\Entity\EntityTypeInterface:  
         in drupal:8.8.0 and is removed from drupal:9.0.0.                                               
         Instead, you should call getSingularLabel().                                                    
         See https://www.drupal.org/node/3075567                                                         
 ------ ------------------------------------------------------------------------------------------------ 

                                                                                                                        
 [ERROR] Found 40 errors
```

### PR DESCRIPTION
**Pull request by arlina-espinoza**
Makes `apigee_edge` module and submodules compatible with Drupal 9, as checked with the deprecation checker tool [`mglaman/drupal-check`](https://github.com/mglaman/drupal-check).

### CODE REVIEW

**Comment by mxr576** [comment]
@cnovak Is this PR going to create a new major version form the module? There are quite some changes on the public API or the module (like new menthods in interfaces, changed return types) that could break downstream projects that were using these. 
(Removing deprecated code usages (which is a :+1: ) does not necessary require adding breaking changes to the codebase, see Drupal core.)

What is the strategy for supporting Drupal 8.x and Drupal 9.x when Drupal 9.0.0 it is out?

**Comment by arlina-espinoza** [comment]
@mxr576 We have discussed creating a new 2.x branch that supports both D8 and D9. However, I have updated the PR and I think there are no breaking changes any more.
Other notes:
- The `Apigee Edge Actions` (rules integration) and submodules are not marked compatible with D9, as rules doesn't have a compatible release yet.

**Testing**
To test against the latest D9 beta, the key module needs this patch (https://www.drupal.org/project/key/issues/3116139). However, applying it using composer patches will still fail because composer says there is no available package of drupal/key compatible for D9. I forked the key module repo to make testing easier, and added it to the repositories section of the composer.json. In all. I'm using the following _composer.json_ template to install and run D9 (it includes some fixes for other dev dependencies that were failing):
https://gist.github.com/arlina-espinoza/70515063318d23d88aabed2b18aac6c8

**Comment by kscheirer** [comment]
Instead of `strtolower()` I suggest using `mb_strtolower()` instead, which is multibyte safe. The change record is here: https://www.drupal.org/node/2850048.

**Comment by arlina-espinoza** [comment]
> Instead of `strtolower()` I suggest using `mb_strtolower()` instead, which is multibyte safe. The change record is here: https://www.drupal.org/node/2850048.

Good catch @kscheirer ! I have updated the PR to use multibyte functions where user input is processed. :+1:

**Review by shadcn — APPROVED** [review]
This looks good. Thanks @arlina-espinoza 

Re. the singular label/lowercase deprecation, I think we should make the change so that `label_singular` annotation on the entity type is lowercase. This is how core does it: https://git.drupalcode.org/project/drupal/-/commit/13822906e5d7704a0df00dbd930b09a71f4b1972

See also `\Drupal\Core\Entity\EntityTypeInterface::getSingularLabel`

```php
/**
   * Gets the indefinite singular form of the name of the entity type.
   *
   * This should return the human-readable name for a single instance of
   * the entity type. For example: "opportunity" (with the plural as
   * "opportunities"), "child" (with the plural as "children"), or "content
   * item" (with the plural as "content items").
   *
   * Think of it as an "in a full sentence, this is what we call this" label. As
   * a consequence, the English version is lowercase.
   *
   * @return string|\Drupal\Core\StringTranslation\TranslatableMarkup
   *   The singular label.
   */
  public function getSingularLabel();
```

**Comment by shadcn** [comment]
@arlina-espinoza Thanks. LGTM.

**Pull request merged**
