### PR TITLE
[#332] Apigee Edge Debug: Display responses as default setting

### LINKED ISSUE #332: Apigee Edge Debug: Display responses as default setting
The formatting when first enabled does not show responses out of the box, so you always need to change the log message format at `/admin/config/apigee-edge/debug` before getting any useful info. Change the module to display responses by default.

### PR DESCRIPTION
**Pull request by arlina-espinoza**
Closes #332 .

### CODE REVIEW

**Review by cnovak — CHANGES_REQUESTED** [review]
Changes look good, but message on screen should be updated:

Screen Shot 2020-03-02 at 9 11 25 AM

How about:
> Note: Adding API responses to log messages by using {response_formatted} token may contain sensitive data (ex.: app credentials, etc.).

**Comment by arlina-espinoza** [comment]
> Changes look good, but message on screen should be updated:
> 
> Screen Shot 2020-03-02 at 9 11 25 AM
> 
> How about:
> 
> > Note: Adding API responses to log messages by using {response_formatted} token may contain sensitive data (ex.: app credentials, etc.).

I've pushed an update fixing that warning! :sweat_smile: Ready for another review.

**Review by cnovak — APPROVED** [review]
LGTM

**Comment by mxr576** [comment]
@cnovak @arlina-espinoza is this PR intentionally does not contain an update hook that would activate this change on existing sites that are using this module?

**Comment by cnovak** [comment]
Good point @mxr576, but I am not sure if we want to mess with the settings if someone changed it already.  What do you think @arlina-espinoza ?

**Comment by mxr576** [comment]
I would only update it if it has not been changed yet.

**Pull request merged**
