### PR TITLE
[DRUP-734] fix issue with Authentication form not saving key

### LINKED ISSUE #176: DRUP-734 \Drupal\apigee_edge\Form\AuthenticationForm does not update key on submit
| Q                           | A
| --------------------------- | -----------------------------------------------
| Bug?                        | yes
| New Feature?                | no
| Module Version              | `8.x-1.x`
| PHP Client version          | `2.0.1`
| Requires PHP client fix     | no

#### Actual Behavior

On submit, the `\Drupal\apigee_edge\Form\AuthenticationForm` does not update the active key.

#### Expected Behavior

The active key should be updated when the `\Drupal\apigee_edge\Form\AuthenticationForm` form is submitted.

#### Steps to Reproduce the behavior

1. Enable Apigee Edge.
2. Visit _/admin/config/system/keys_ and edit the default key.
3. Select *Configuration* as the key provider.
4. Add credentials and save. Credentials are saved successfully.
5. Visit _/admin/config/apigee-edge/settings_
6. Enter credentials and save.
7. Credentials are *NOT* updated.

#### Proposed Solution

Replace

https://github.com/apigee/apigee-edge-drupal/blob/9e753e8f8f390489dea2e2ec38571a13563bdb5f/src/Form/AuthenticationForm.php#L361-L364

With

```
$this->activeKey->setKeyValue($processed_submitted);
$this->activeKey->save();
```

`$this->activeKey->save()` will call the `keyProvider->setKeyValue` automatically. See `\Drupal\key\Entity\Key::preSave`

### PR DESCRIPTION
**Pull request by shadcn**
Fixes #176 

(Needs tests)

### CODE REVIEW

**Comment by mxr576** [comment]
Confirmed, @arshad please add a test case to the AuthenticationFormJsTest that uses the Configuration key provider as a key provider.

**Comment by shadcn** [comment]
@mxr576 For some reasons `$this->assertSession()->pageTextContains('The selected key provider does not accept a value. See the provider\'s description for instructions on how and where to store the key value.');` is failing for me when I run the `\Drupal\Tests\apigee_edge\FunctionalJavascript\Form\AuthenticationFormJsTest::testAuthenticationForm`.

I'll see if I can take a look at the tests later this week.

**Comment by mxr576** [comment]
@arshad Do not spend time on this, I'll try to address this with the fix for #178.

**Comment by mxr576** [comment]
Closing in favor of #179

**Pull request closed without merging**
